name: android-CI

on:
  push:
    branches:
      - version-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java SDK setup
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'gradle'
      - name: do permission for the file
        run: chmod +x gradlew
      - name: Create ApiKeyy
        run: |
            mkdir -p app/src/main/java/com/example/myapplication/Api
            cat > app/src/main/java/com/example/myapplication/Api/ApiKeyy.kt <<EOF
            package com.example.myapplication.Api

            class ApiKeyy {
                companion object {
                    val api_key = "${{ secrets.api_key }}"
                }
            }
            EOF
      - name: Build with Gradle
        run: ./gradlew assembleDebug
