name: movie-android-CI

on:
  push:
    branches:
      - version-2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Java SDK setup
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: 'gradle'
      - name: do permission for the file
        run: chmod +x gradlew
      - name: Build with Gradle
        env:
            api_key: ${{ secrets.TMDB_API_KEY }}
        run: ./gradlew assembleDebug
