# This is a basic workflow to help you get started with Actions

name: test-for-mobile

on:
  workflow_run:
    workflows: ["android-CI"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - run: echo "Workflow build is done"

      - name: Getting Repo
        uses: actions/checkout@v4

      - name: Installing JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "gradle"

      - name: Add permission for Gradle
        run: chmod +x gradlew
      - name: Create ApiKeyy
        run: |
            mkdir -p app/src/main/java/com/example/myapplication/Api
            cat > app/src/main/java/com/example/myapplication/Api/ApiKeyy.kt <<EOF
            package com.example.myapplication.Api

            class ApiKeyy {
                companion object {
                    val api_key = "${{ secrets.api_key }}"
                }
            }
            EOF

      - name: Run Unit tests
        run: ./gradlew test
      
