name: test-mobile

on:
  workflow_run:
    workflows: ["android-CI"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - run: echo "Workflow build is done"

      - name: Getting Repo
        uses: actions/checkout@v4

      - name: Installing JDK
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "22"
          cache: "gradle"

      - name: Add permission for Gradle
        run: chmod +x gradlew

      - name: Run tests
        run: ./gradlew test
